// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-mock-key-for-local-fallback',
    appId: '1:1234567890:web:mockid',
    messagingSenderId: '1234567890',
    projectId: 'libreflow-library-app',
    authDomain: 'libreflow-library-app.firebaseapp.com',
    storageBucket: 'libreflow-library-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-mock-key-for-local-fallback',
    appId: '1:1234567890:android:mockid',
    messagingSenderId: '1234567890',
    projectId: 'libreflow-library-app',
    storageBucket: 'libreflow-library-app.appspot.com',
  );
}
